<a href="https://colab.research.google.com/github/azureice10/android/blob/master/Windows.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# melakukan ekstraksi pada file zip
import zipfile,os
local_zip = '/content/windows.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/content/')

In [5]:
import pandas as pd
df = pd.read_csv('windows.csv')

In [6]:
df = df.drop('hash', axis=1)

In [7]:
df.head()

   t_0  t_1  t_2  t_3  t_4  t_5  ...  t_95  t_96  t_97  t_98  t_99  malware
0  112  274  158  215  274  158  ...   215    35   208    56    71        1
1   82  208  187  208  172  117  ...   297   135   171   215    35        1
2   16  110  240  117  240  117  ...   112   123    65   113   112        1
3   82  208  187  208  172  117  ...   187   208   302   228   302        1
4   82  240  117  240  117  240  ...   260   141   260   141   260        1

[5 rows x 101 columns]

In [8]:
    # memisahkan atribut pada dataset dan menyimpannya pada sebuah variabel
    X = df[df.columns[:100]]
     
    # memisahkan label pada dataset dan menyimpannya pada sebuah variabel
    y = df['malware']

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

print("Number transactions X_train dataset: ", X_train.shape)
print("Number transactions y_train dataset: ", y_train.shape)
print("Number transactions X_test dataset: ", X_test.shape)
print("Number transactions y_test dataset: ", y_test.shape)

Number transactions X_train dataset:  (30713, 100)
Number transactions y_train dataset:  (30713,)
Number transactions X_test dataset:  (13163, 100)
Number transactions y_test dataset:  (13163,)

In [12]:
from sklearn.model_selection import train_test_split
X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size=0.2, random_state=0)

print("Number transactions X_train dataset: ", X_train.shape)
print("Number transactions y_train dataset: ", y_train.shape)
print("Number transactions X_val dataset: ", X_val.shape)
print("Number transactions y_val dataset: ", y_val.shape)
print("Number transactions X_test dataset: ", X_test.shape)
print("Number transactions y_test dataset: ", y_test.shape)

Number transactions X_train dataset:  (30713, 100)
Number transactions y_train dataset:  (30713,)
Number transactions X_val dataset:  (10530, 100)
Number transactions y_val dataset:  (10530,)
Number transactions X_test dataset:  (2633, 100)
Number transactions y_test dataset:  (2633,)

In [15]:
from imblearn.over_sampling import SMOTE

print("Before OverSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train==0)))

sm = SMOTE(random_state=2)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel())

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res==0)))

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)

Before OverSampling, counts of label '1': 29971
Before OverSampling, counts of label '0': 742

After OverSampling, the shape of train_X: (59942, 100)
After OverSampling, the shape of train_y: (59942,)

After OverSampling, counts of label '1': 29971
After OverSampling, counts of label '0': 29971

In [16]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
clf.score(X_train,y_train)

0.9992185719402208

In [16]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Dense , Input , LSTM , Embedding, Dropout , Activation, GRU, Flatten
from keras.layers import Bidirectional, GlobalMaxPool1D
from keras.models import Model, Sequential
from keras.layers import Convolution1D
from keras import initializers, regularizers, constraints, optimizers, layers


embed_size = 128
model = Sequential()
model.add(Embedding(5000, 32))
model.add(Bidirectional(LSTM(32, return_sequences = True)))
model.add(GlobalMaxPool1D())
model.add(Dense(20, activation="relu"))
model.add(Dropout(0.05))
model.add(Dense(1, activation="sigmoid"))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
embedding_5 (Embedding)      (None, None, 32)          160000
_________________________________________________________________
bidirectional_5 (Bidirection (None, None, 64)          16640
_________________________________________________________________
global_max_pooling1d_5 (Glob (None, 64)                0
_________________________________________________________________
dense_10 (Dense)             (None, 20)                1300
_________________________________________________________________
dropout_5 (Dropout)          (None, 20)                0
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 21
=================================================================
Total params: 177,961
Trainable params: 177,961
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model.predict(X_test)